name: Go
on:
  push:
    branches:
    - master
  pull_request: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.18'
        - '1.19'
        - '1.20'
        - '1.21'
        goenv:
        - GOARCH=amd64
        - GOARCH=arm GOARM=5
        - GOARCH=arm GOARM=6
        - GOARCH=arm GOARM=7
        - GOARCH=arm64
        - GOARCH=riscv64
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v1
    - run: go generate ./...
    - run: ${{ matrix.goenv }} go build ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.19'
        - '1.20'
        - '1.21'
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v1
    - run: go generate ./...
    - run: go test -race -v ./...
